services:
  - type: web
    name: video-fetcher
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free 